### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by midiway** [Robmaister/SharpFont#62] opened 2016-03-04 14:38 UTC
I am able to build and run the Example project on OSX, but I get the following output:
![captura de tela 2016-03-04 as 11 36 41](https://cloud.githubusercontent.com/assets/493743/13529948/8dda3384-e1fd-11e5-9691-42625953c9d9.png)
maybe some simple background brush issue because glyphs box seems to be rendered...

**Comment by midiway** [comment] 2016-03-04 14:45
Examples/Program.cs line 126, replace with:
```Bitmap cBmp = ftbmp.ToGdipBitmap(Color.Red);```
and got:
![captura de tela 2016-03-04 as 11 44 00](https://cloud.githubusercontent.com/assets/493743/13530121/9119d0c6-e1fe-11e5-8ae9-faa4918f6fda.png)

**Comment by Robmaister** [comment] 2016-03-04 15:19
Duplicate of #55. This is a bug in libgdiplus that never sets the proper flags for the color palette, which makes the renderer assume that there is no transparency. I can work the solution into the next version of SharpFont, but Linux & Mac users will likely take a moderate performance hit since it relies on reflection.

If you want to patch it yourself right now, add the following line just before `bmp.Palette = palette` for all cases except LCD.

    typeof(ColorPalette).GetField ("flags", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).SetValue (palette, palette.Flags | 1);

**Comment by Robmaister** [comment] 2016-03-04 15:21
Note that this has already been submitted to Xamarin with no response. I may try to find the root cause (where the flags get set in Windows GDI+ vs Mono) and submit a PR.

**Comment by HinTak** [comment] 2016-04-26 14:43
Interesting, I am about to submit a similar issue on linux - I saw it last summer, just haven't bother enough to file. How does one do inline images here?

Top is is wine + dotnet2 + MS libgdiplus (wine's gdiplus does not work correctly with wine + dotnet2), bottom is linux mono 4.2.2.30 and libgdiplus 3.12 .

http://htl10.users.sourceforge.net/tmp/Screenshot%20from%202016-04-26%2015-24-52.png

**Comment by HinTak** [comment] 2016-04-26 14:45
In addition to how it looks on mac, the font chooser's background does not work on linux either.

**Comment by HinTak** [comment] 2016-04-26 16:26
I have uploaded my wine + mono screenshot as
https://bugzilla.xamarin.com/attachment.cgi?id=15847 under
https://bugzilla.xamarin.com/show_bug.cgi?id=37608#c1

**Comment by Robmaister** [comment] 2016-04-27 02:12
Yeah the extra Linux issues are probably attributed to winforms problems in Linux, which can be solved either by using functionally equivalent components (ListView vs ListBox, etc.) or by trying to solve the problems within Mono's wrapper.

Besides that this is a pretty clear-cut regression of libgdiplus to the original MS GDI+

**Comment by HinTak** [comment] 2016-04-27 18:40
I don't think it is called a "regression" - libgdiplus is incomplete, it just doesn't imitate MS GDI+ in every way, understandably.

The problem with the left side font selection on linux seems to be a case of lack of initialization somewhere - if I just blindly click on it, it would sometimes comes back with the correct black-letter-on-white-background look. Also File->Open Menu is active but invisible(!), and the file-open dialog box is not drawn correctly.

All in all, the example is simply not very usable on Linux. I am somewhat surprised that it works better on Mac OS X though.

**Comment by Robmaister** [comment] 2016-04-28 20:07
I guess "regression" may not be the best term, but incompatibility with the results of the original implementation of the API they are implementing. GDI+ properly flags my bitmap as one with alpha values while libgdiplus stores the alpha values but ignores them because an internal flag is never set.

Last I checked (which admittedly, was a long time ago) winforms was supposed to ["just work"](http://www.mono-project.com/docs/gui/winforms/) on Linux and OS X, but perhaps this is no longer the case (or I'm using components that don't play well with Mono's winforms implementation). The GUI was created with Visual Studio's drag-and-drop winforms editor. I'm open to switching the example GUI project to another platform that works well cross-platform.

**Comment by HinTak** [comment] 2016-04-29 00:16
"Just work" is a marketing term :-). In reality, I believe, both liibgdiplus and xarmarin/mono's winforms work well enough for many common usage scenarios, but show some limitations where deeper and more obscure api's are concerned. To mono's team credit (they have renamed themselves a few times... Ximian, Novell, now Xamarin), they have done a lot of good work, but just as any emulation technology and cross-platform technology goes, there are (1) catching up to do - api's are implemented based on popularity and likelihood of usage, (2) sometimes it is not easy to achieve full equivalent functionality on all platforms.

Transparent/Semi-transparent GUI elements are definitely one of the weaker part of Mono's libgdiplus /winforms, because it is simply a difficult problem to have semi-transparent widgets in a cross-platform manner.

The current sample is pretty when it works (i.e. on windows); I think it should be kept; but it would be nice to have another one, or a variant, which caters for mono's limitations.

I'll have a look and see if I can identify all the parts which does not work well with mono, and come up with a variant.

**Comment by HinTak** [comment] 2016-04-29 01:12
if you have to add mono-specific workarounds, the recommended approach is to do do

```
if ( Type.GetType("Mono.Runtime") != null )
```

to detect whether the current app is running under dotnet or mono.

**Comment by Robmaister** [comment] 2016-04-29 02:31
I believe Xamarin was just recently purchased by Microsoft, and yes, much credit to the team for providing an already exceptional piece of software. The goal would be to provide an implementation with the same (or better) results than the original one, but I do understand that in certain edge cases things will break, hence the bug report.

In this particular case, the transparent Bitmap rendering works just fine, it's the conversion from an 8bpp indexed bitmap to a 32bpp BGRA bitmap that doesn't.

If there are a few small workarounds with Winforms I can apply on Mono, I'll go ahead and apply them while checking for the Mono runtime. Otherwise, I'd rather move to a GUI platform that will work as expected cross-platform, since I spend most of my time in Windows anyways for work. Eto Forms and XWT both look simple enough for this example project.

**Comment by HinTak** [comment] 2016-04-29 05:45
Strangely enough, if I start the example with an empty Font directory, and add open afterwards (with my new enhancement https://github.com/Robmaister/SharpFont/issues/69 ) - it works a lot better on linux:

- the menu items are drawn correctly (start with the original Fonts/, I can click blindly and have effect, but the menu are not drawn).
- the list box is drawn and updated on clicks correctly. ( start with the original Fonts/, it stays black)
- the open file dialog box is drawn correctly, and I can select fonts - whether selecting has effect or not depends on the new enhancement :-) ( start with the original Fonts/, I can blindly select it, and it would launch, but the file dialog is not painted - it is just a modal corrupted window)

So a rather interesting issue is that the example seems to behave differently depends on whether there are fonts in Fonts/ .

**Comment by HinTak** [comment] 2016-04-29 07:11
I had my reservation a bit abou a workaround since ToGdipBitmap() seems to get called very often, but it does not to be - if you merge https://github.com/Robmaister/SharpFont/pull/70/commits/625d7c347161d5b6d153061bf23b6643a20724aa . It only needs to be called per font change, not per paint event!

So how do you feel about this?
```
diff --git a/Source/SharpFont/FTBitmap.cs b/Source/SharpFont/FTBitmap.cs
index b6dad49..53745af 100644
--- a/Source/SharpFont/FTBitmap.cs
+++ b/Source/SharpFont/FTBitmap.cs
@@ -441,6 +441,11 @@ namespace SharpFont
                                                palette.Entries[i] = Color.FromArgb(i, (int)(color.R * a), (int)(color.G * a), (int)(color.B * a));
                                        }
 
+                                       if ( Type.GetType("Mono.Runtime") != null )
+                                               typeof(ColorPalette).GetField ("flags",
+                                                       System.Reflection.BindingFlags.Instance |
+                                                       System.Reflection.BindingFlags.NonPublic).SetValue (palette,
+                                                       palette.Flags | 1);
                                        bmp.Palette = palette;
                                        return bmp;
                                }

```

**Comment by Robmaister** [comment] 2016-04-29 22:52
oh wow, didn't even realize I was recreating the bitmap per-paint, how silly of me. Glad it's working better now.

The patch looks fine, I may pull the Type.GetType and GetField bits out to lazy-loaded static variables to reduce the amount of reflection done per call. I know that generally ToGdipBitmap shouldn't be in a program's hot path, but a lot of times for simple uses it will be. I'll whip that up right now.

**Comment by Robmaister** [comment] 2016-04-29 23:03
@HinTak Give that a shot, I don't have access to a Linux or OS X box at the moment.

**Comment by HinTak** [comment] 2016-04-29 23:17
Yes, work perfectly on linux now.

I am a bit curious why working around the alpha conversion also fixes the menu/file-dialog drawing issue (that in itself is strange as drawing glyphs on start affects drawing menus/file-dialogs). How did you debug libgdiplus?

Anyway, I think this can close.

**Comment by Robmaister** [comment] 2016-04-30 00:11
I'd bet the two bugs are unrelated, drawing the text during OnPaint was likely pegging the thread and causing the rest of the GUI to freak out.

Originally the examples project was a small command-line utility that was hardcoded to produce a single string with a single font and output a separate bitmap. It's why RenderString is still inside of Program.cs, so I just temporarily commented out Application.Run() in Main and replaced it with a call to RenderString and saved the Bitmap out to a file that I could inspect. Once I saw that the Windows bitmap had alpha values, but the Linux one did not, I took a peek through the Mono source, which lead me to the libgdiplus source. I described the code I looked through in this comment on #55: https://github.com/Robmaister/SharpFont/issues/55#issuecomment-152707144

I scanned through the rest of the libgdiplus source code looking for ways to have the flags include PixelFlagsHasAlpha for the particular BItmap format I had chosen (which most closely resembles the pixel format FreeType returns) and couldn't find anything. To top it off, the field was read-only, so I figured the only way it would work properly was with reflection. I rendered out and saved a new bitmap with the flag set and it perfectly matched the bitmap produced on Windows. No need to step through or compile libgdiplus in any special way, it was pretty clear that without that flag, all of the alpha values were being OR'd with 0xFF which is definitely not what I want.

**Comment by Robmaister** [comment] 2016-04-30 00:13
Anyways, yes I'll close this issue but keep #55 open until the Xamarin bug report gets resolved (or at least a response) or a PR gets submitted to libgdiplus,

**Comment by midiway** [comment] 2016-04-30 00:13
ok

**Closed by Robmaister** 2016-04-30 00:13 UTC

**Comment by HinTak** [comment] 2016-04-30 00:41
> I'd bet the two bugs are unrelated, drawing the text during OnPaint was likely pegging the thread 
> and causing the rest of the GUI to freak out.

You are right! I went back to f0bdb22636e7a5e3a6f7fa131d85220d600adedb (before this bunch of changes) and just cherry-pick only my re-paint fix on top, and going back and forth on that one particular change; I get the Mac OS X look like at the beginning of this thread with the repaint fix, but the bottom of https://bugzilla.xamarin.com/attachment.cgi?id=15847 and all the menu/file-dialog drawing problems without it. So it is indeed the crazy OnPaint redrawing starving all the other screen-drawing tasks on Linux. And Mac OS X seems to handle the starvation better (or fairer...).
